# Generated by Django 4.1.5 on 2023-02-27 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 6, 26, 36, 568242, tzinfo=datetime.timezone.utc)),
        ),
    ]
