# Generated by Django 4.1.5 on 2023-02-28 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_blog_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 4, 17, 1, 63821, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 4, 17, 1, 64100, tzinfo=datetime.timezone.utc)),
        ),
    ]
