# Generated by Django 4.1.5 on 2023-03-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_author_created_at_author_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='brithdate',
            new_name='birthdate',
        ),
    ]
