# Generated by Django 4.1.7 on 2023-03-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_blog_options'),
        ('myapp', '0011_rename_comments_comment_and_more'),
    ]

    operations = [
    ]
