name: BLOG-APP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: MacOS-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          python manage.py test blog.tests